import React from "react";
import { createRoot } from "react-dom/client";
import "./tailwind.css"; // generated by the Tailwind CLI (tw:build / tw:watch)
import App from "./App.jsx";

const root = createRoot(document.getElementById("root"));
root.render(<App />);
